### ISSUE TITLE
exception in request.js with empty or broken image

### ISSUE THREAD

**Issue by nymo** [nymo/gulp-tinypng-extended#9]
When you try to send an empty or broken image to the api the plugin crashes with an exception error in the request.js file

**request.js:629
      throw new Error('Argument error, options.body.')
      ^
Error: Argument error, options.body.**

**Comment by nagman** [comment]
This error still happens today...

**Comment by nymo** [comment]
@nagman do you have some examples? I'm using the library in production and empty images are being skipped and the job continues with the next image.

**Comment by nagman** [comment]
@nymo Actually, the bug is not related to broken images. I don't understand why it's happening.
I have a folder with svg, png and jpg images, and a subfolder with others jpg.
I took care to trigger tinypng only on png and jpg files, but when gulp batches the folder, this same bug (request.js:629) happens - either at the beginning or at the end.

I would need to dive into it and find a clue or something but I don't have the time for now. So I'll just skip this gulp task and come back to it when I'm done, and I'll tell you if I have more clues.
